actionsの修正

diff --git a/.github/workflows/deployMain.yaml b/.github/workflows/deployMain.yaml
--- a/.github/workflows/deployMain.yaml
+++ b/.github/workflows/deployMain.yaml
@@ -79,3 +79,8 @@ jobs:
           echo "| | | "  >> $GITHUB_STEP_SUMMARY
           echo "|---|---|"  >> $GITHUB_STEP_SUMMARY
           echo "| Deploy Log | $DEPLOY_LOG_URL | "  >> $GITHUB_STEP_SUMMARY
+      - name: Error handling
+        if: ${{ job.status == 'failure' }}
+        run: |
+          echo "Error handling"
+          exit 1
